image: node:18

cache:
  paths:
    - node_modules/

stages:
  - deploy

pages:
  stage: deploy
  only:
    - master
  script:
    - npm ci --ignore-scripts
    - npm run docs:build
    - mv docs/.vuepress/dist public
  artifacts:
    paths:
      - public
